### ISSUE TITLE
More information about releases

### ISSUE THREAD

**Issue by fangly** [biocore/tax2tree#19]
Hi,

I would like to give tax2tree a try, but I am a bit confused about its different releases.

There is a single release on Sourceforge, 1.0, yet the ChangeLog also mentions a 1.1-dev release, which is not on SourceForge. Since there are no dates on the ChangeLog, I also have no idea how up-to-date these releases are. As a result, I am not quite sure if I should run 1.0, 1.1-dev, or even try the latest development code.

Could you please make the releases and the ChangeLog consistent, and add release dates?

Cheers,

Florent

**Comment by wasade** [comment]
Date added to change log for pending release. The release information will be part of the automated pypi process, and the github release
